[package]
name = "kernel"
version = "0.1.0"
authors = ["GrayJack <gr41.j4ck@gmail.com>"]
edition = "2018"

[package.metadata.bootimage]
default-target = "kernel.json"

[package.metadata.bootimage.bootloader]
name = "bootloader"
target = "x86_64-bootloader.json"

[workspace]

[dependencies]
bootloader = "^0.3.12"
bitflags = "^1.0.4"
x86_64 = "^0.3.4"
spin = "^0.5.0"
lazy_static = { version = "^1.2.0", features = ["spin_no_std"] }

[[bin]]
name = "kernel"
test = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
